# This is a basic workflow to help you get started with Actions

name: Android CI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
 build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }} 
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
    - run: ls 
    - run: cp "README.md" "build\app\outputs\apk\release\README.md" 
    - run: flutter pub get
    - run: flutter build apk
    - run: ls 
#     - name: Copy file
    - run: cp "build\app\outputs\apk\release\app-release.apk" "android\build\app\outputs\apk\release\app-release.apk" 
      
    - name: Deploy to Firebase
      run: bash ./android/gradlew appDistributionUploadRelease
