# This is a basic workflow to help you get started with Actions

name: Android CI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
 build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
    - run: cp "coin_app.iml" "coin_app.iml" 
    - run: flutter pub get
    - run: flutter build apk
      
#     - name: Copy file
    - run: cp "build\app\outputs\apk\release\app-release.apk" "android\build\app\outputs\apk\release\app-release.apk" 
      
    - name: Deploy to Firebase
      run: bash ./android/gradlew appDistributionUploadRelease
