# This is a basic workflow to help you get started with Actions

name: Android CI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
 build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
#     - run: ls 
#     - run: cp "README.md" "build\app\outputs\apk\release\README.md" 
    - run: flutter pub get
    - run: flutter build apk
#     - run: ls 
#     - name: Copy file
#     - run: cp "build\app\outputs\apk\release\app-release.apk" "android\build\app\outputs\apk\release\app-release.apk" 
      
    - name: Deploy to Firebase
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: testers
        release_notes: "a new version"
        file: build/app/outputs/apk/release/app-release.apk
